from ultralytics import YOLO
import os

def evaluate_models():
    # Define the paths to the best weights generated by your training scripts.
    # Adjust these paths if your training runs were saved in different directories.
    models_to_test = {
        "YOLOv26_Nano": "/home/gnanateja/drone_project/yolo_versions_check/runs/detect/drone_project_yolo26n/weights/best.pt",
        "YOLOv26_Small": "/home/gnanateja/drone_project/yolo_versions_check/runs/detect/drone_project_yolo26s/weights/best.pt",
        "YOLOv26_Medium": "/home/gnanateja/drone_project/yolo_versions_check/runs/detect/drone_project_yolo26m/weights/best.pt"
        # The Medium model is commented out until we find where it saved, or until it finishes training!
        # "YOLOv26_Medium": "INSERT_PATH_LATER" /home/gnanateja/drone_project/yolo_versions_check/runs/detect/drone_project_yolo26m
    }

    yaml_path = 'data.yaml'

    for model_name, weight_path in models_to_test.items():
        print(f"\n==================================================")
        print(f"Starting Evaluation for: {model_name}")
        print(f"==================================================")
        
        if not os.path.exists(weight_path):
            print(f"Error: Could not find weights at {weight_path}. Skipping.")
            continue

        # 1. Load the trained model
        model = YOLO(weight_path)

        # 2. Run the validation process
        # This automatically uses the 'val' dataset path defined in your data.yaml
        metrics = model.val(
            data=yaml_path,
            split='val',     # Explicitly tell it to use the validation set
            conf=0.25,       # Baseline confidence threshold for evaluation
            iou=0.6,         # Intersection Over Union threshold (how tight the box must be)
            plots=True       # Generates visual graphs (PR curves, Confusion Matrix)
        )

        # 3. Print the core metrics directly to the terminal
        print(f"\n--- Results for {model_name} ---")
        print(f"Mean Average Precision (mAP50-95): {metrics.box.map:.4f}")
        print(f"mAP at 50% IoU (mAP50): {metrics.box.map50:.4f}")
        print(f"Precision: {metrics.box.mp:.4f} (at default confidence)")
        print(f"Recall: {metrics.box.mr:.4f} (at default confidence)")
        
        # The save directory for the full report
        print(f"Full visual report saved to: {metrics.save_dir}")

if __name__ == "__main__":
    evaluate_models()